name: "exp_sim_binary_m2"
models: ["propensity", "m1", "m2", "y"]
seed: 0
num_samples: 30
tuning_ranges:
  mlp:
    epochs: [30]
    batch_size: [32, 64, 128]
    lr: [0.0005, 0.001, 0.005]
    d_hidden: [5, 10, 20, 30]
    dropout: [0, 0.1]
  nf:
    epochs: [50]
    batch_size: [32, 64, 128]
    lr: [0.0005, 0.001, 0.005]
    d_hidden: [5, 10, 20, 30]
    count_bins: [2, 4, 8]



