name: "exp_ihdp"
models: ["propensity", "y"]
seed: 0
num_samples: 40
tuning_ranges:
  mlp:
    epochs: [100]
    batch_size: [32, 64, 128]
    lr: [0.0005, 0.001, 0.005]
    d_hidden: [5, 10, 20]
    dropout: [0, 0.1, 0.2]
  nf:
    epochs: [50]
    batch_size: [32, 64, 128]
    lr: [0.0005, 0.001, 0.005]
    d_hidden: [3, 5, 10]
    count_bins: [1, 2, 3, 4]


